### ISSUE TITLE
Create a very small file on mediaflux

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/tiger-data-experiments#14]
- [ ] Given a file ("Hello word") ingest (?) it into media flux,
- [ ] and read the content back out
- [ ] with a single ruby script.

**Comment by mccalluc** [comment]
I believe [Hector's PR](https://github.com/pulibrary/tiger-data/pull/22/files#diff-3510072ec6d8d4497832e1ee95062d972e2563d6b7466b92d40d9ab4e0765756R111-R127) gives us the machinery for this, but it doesn't check off the boxes: We could build on top of it.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/tiger-data/pull/24/files#r1017107239 definitely indicates that there needs to be some further documentation addressing these string values.

**Comment by hectorcorrea** [comment]
See code that @carolyncole implemented using `multipart/form-data` encoding (instead of DIME) based on the Mediaflux Developer Guide (page 143): https://github.com/pulibrary/tiger-data-experiments/pull/45

**Comment by hectorcorrea** [comment]
I did not find in the Developer Guide a way to download the content of a file using `multipart/form-data` encoding, but I am pretty sure there is one. 

I will suggest we wait until we have a developer session with Arcitecta and ask about this. 

We already have have a way to download content (using the DIME format) if we have to (see `http_post` in https://github.com/pulibrary/tiger-data-experiments/blob/50dc63dbb0fe840cfbf2b030222cc8babae822de/ruby-hardcoded-api/mfclient.rb)
