### ISSUE TITLE
Review TigerData Samvera Connect presentation

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-experiments#7]
Review Samvera Connect presentation materials:

* [Slides](https://docs.google.com/presentation/d/17cnOj3Gh8wL_ZLlyQiQV4K_1UiirumzzKCWij7dZTyc/edit#slide=id.p)
* [Recording](https://youtu.be/T9SOULXnXME?t=6729)

## Acceptance criteria
- [x] Hector
- [x] James
- [x] Carolyn
- [x] Chuck
- [x] Kate
- [x] Bess
- [ ] Tyler

**Comment by carolyncole** [comment]
This was an interesting presentation.  It's good to see how we are fitting into the larger picture.
