### ISSUE TITLE
Define the questions for this spike

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tiger-data-experiments#8]
Based on [kick-off meeting](https://docs.google.com/document/d/1i0VucwMIcoqYojsztU8YadsJOQhGJKDEKsJcbkc1I7o/edit#heading=h.4bbiey9p8sk7), define the questions to be answered in this spike.

Doing an initial brain storming: https://docs.google.com/document/d/1PvmA5ekEsx5NSRV_P8p_6F6BTv_z2LR_hXqTgGmNXG4/edit#

- [x] Carolyn will set up a meeting for moving the ideas into tickets and discussion.
- [ ] We want a refined set of questions

**Comment by bess** [comment]
We made some tickets, but we are unsure what the goals of this spike are so we don't know whether we can close this ticket.

**Comment by carolyncole** [comment]
We are closing this because the Spike ended
